version: '3.7'

services:
  frontend:
    restart: unless-stopped
    image: naica922/uek223_extended_frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:80
  backend:
    restart: unless-stopped
    image: naica922/uek223_extended_backend:latest
    container_name: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      LOGGING_LEVEL_ROOT: info
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      JWT_ISSUER: uk223
      JWT_EXPIRATION_MILLIS: 100000000
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data