name: frontend
on: push
jobs:
  Script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
      - uses: actions/setup-node@v4
      - with:
      - node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: naica922
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./react_frontend/.
          push: true
          tags: naica922/uek223_extended_frontend:latest

      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo "Hello World"